name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

  deploy:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Restart application service
      run: sudo systemctl restart bot.service
